# Generated by Django 6.0 on 2025-12-14 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentary',
            old_name='text',
            new_name='content',
        ),
    ]
