# Generated by Django 6.0 on 2025-12-14 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_owner_comment_author_rename_owner_post_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Commentary',
        ),
        migrations.AlterModelOptions(
            name='commentary',
            options={'verbose_name_plural': 'Commentaries'},
        ),
    ]
