# Generated by Django 6.0 on 2025-12-14 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_author_post_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentary',
            old_name='author',
            new_name='user',
        ),
    ]
