# Generated by Django 6.0 on 2025-12-14 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_author_commentary_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentary',
            old_name='text',
            new_name='content',
        ),
    ]
